### ISSUE TITLE
failing tests

### ISSUE THREAD

**Issue by dereke** [bdimcheff/google4r-checkout#3]
Hi,
I would like to make some changes to the library but nearly all the tests are failing right now.
Is there something I am doing wrong? A missing dependency?

Thanks,
Derek

**Comment by bdimcheff** [comment]
Hm, I'm not sure I ever ran the tests on this before.  I yanked it from Google's svn repo a while back, I think.  I needed to use it in bundler, so I just stuck it up on github.  It looks like this guy is keeping a more updated version.  Have you checked this out? https://github.com/nbudin/google4r-checkout

**Comment by dereke** [comment]
Ahh that does seem a bit more up to date!
Thanks I will check it out.
